version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=autoflex_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoflex-api
    ports:
      - "${EXPOSE_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/autoflex_db
      - SPRING_DATASOURCE_USERNAME=devuser
      - SPRING_DATASOURCE_PASSWORD=devpass
      - EXPOSE_PORT=${EXPOSE_PORT}